sudo: false
language: node_js
node_js:
  - '10'
cache:
  directories:
    - '$HOME/.npm'
    - node_modules
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: release
      if: branch = main
      node_js: lts/*
      before_install: skip
      script:
        # Update Tables of Content in the relevant `.md` files
        - markdown-toc -i CONTRIBUTING.md
        - markdown-toc -i README.md
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run test && npm run build && npm run semantic-release && npm run test:coverage:send
        on:
          branch: main
